---
dependencies: []

galaxy_info:
  author: Carl Buchmann
  description: Installs and configures Xrdp
  company: none
  license: "license (BSD, MIT)"
  min_ansible_version: 2.6
  platforms:
    - name: EL
      version:
        - 7
  galaxy_tags:
    - xrdp
    - centos
    - rhel