- hosts: localhost

  tasks:
 
  - name: Install XRDP
    include_role:
       name: xrdp

  - name: Install Visual Studio Code
    include_role:
       name: vscode

  - name: Install Git
    include_role:
       name: git

  - name: Install PowerShell
    include_role:
       name: powershell

  - name: Install ARA Records Ansible
    include_role:
       name: ara

  - name: Deploy latest version of ansible, enable windows remote management with kerberos and install various module dependencies
    include_role:
       name: ansible-engine

