- hosts: localhost
  become: true

  tasks:

    - name: Install Git
      import_role:
        name: git
      tags: git

    - name: Install XRDP
      import_role:
        name: xrdp
      tags: xrdp

- hosts: localhost

  tasks:

    - name: Install Visual Studio Code
      import_role:
        name: vscode
      tags: vscode
