---

# Update Git Version Centos/RedHat

- name: enable WANDisco's repo for access to latest Git version
  package:
    name: http://opensource.wandisco.com/centos/7/git/x86_64/wandisco-git-release-7-2.noarch.rpm
    state: present

- name: Update Git version
  package:
    name: git
    state: latest