---
# Load environment specific variables

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Enable extras repo required for various packages - RedHat OS Family only
- name: enable extras repo
  become: true
  package:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

# Install Python requirements
- name: install python tools and cryptography
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ python_tools }}"

# Configure Ansible to support Windows Remote management with Kerberos Authentication
- name: install kerberos libraries dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ kerberos_libraries }}"

- name: install python winrm and kerberos dependencies
  become: true
  pip:
    name:
      - pywinrm
      - pywinrm[kerberos]
      - pykerberos>=1.2.1
      - requests-kerberos
      - requests-ntlm

- name: Configure Kerberos reamls
  become: true
  template:
    src: kerberos-reamls.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644

# Install various python libraries for module support

- name: install ansible microsoft azure dependencies
  become: true
  pip:
    name: ansible[azure]

- name: upgrade jinja2 to 2.10 or later
  become: true
  pip:
    name: Jinja2>=2.10

- name: install napalm-ansible
  become: true
  pip:
    name:
      - napalm-ansible
      - python-gssapi

- name: install network address filter
  become: true
  pip:
    name: netaddr

- name: install F5 dependencies
  become: true
  pip:
    name:
      - f5-sdk
      - bigsuds
      - deepdiff

- name: install AWS dependencies
  become: true
  pip:
    name:
      - boto
      - boto3
      - botocore

- name: install Google Cloud dependencies
  become: true
  pip:
    name:
      - apache-libcloud
      - boto
      - google-auth
      - google-cloud-pubsub


# Upgrade ansible to latest stable version published in EPEL repo
- name: upgrade ansible to latest version
  become: true
  package:
    name: ansible
    state: latest
