---
# Load environment specific variables

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Enable extras repo required for various packages - RedHat OS Family only
- name: enable extras repo
  package:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

# Install Python requirements
- name: install python tools and cryptography
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ python_tools }}"

# Configure Ansible to support Windows Remote management with Kerberos Authentication
- name: install kerberos libraries dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ kerberos_libraries }}"

- name: install python winrm and kerberos dependencies
  pip:
    name: "{{ item }}"
  with_items:
    - pywinrm
    - pywinrm[kerberos]
    - pykerberos>=1.2.1
    - requests-kerberos
    - requests-ntlm

- name: Configure Kerberos reamls
  template:
    src: kerberos-reamls.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644

# Install various python libraries for module support

- name: install ansible microsoft azure dependencies
  pip:
    name: ansible[azure]

- name: upgrade jinja2 to 2.10 or later
  pip:
    name: Jinja2>=2.10

- name: install napalm-ansible
  pip:
    name: napalm-ansible

- name: install network address filter
  pip:
    name: netaddr

- name: install F5 dependencies
  pip:
    name: "{{ item }}"
  with_items:
    - f5-sdk
    - bigsuds
    - deepdiff

- name: install AWS dependencies
  pip:
    name: "{{ item }}"
  with_items:
    - boto
    - boto3
    - botocore

- name: install Google Cloud dependencies
  pip:
    name: "{{ item }}"
  with_items:
    - apache-libcloud
    - boto
    - google-auth
    - google-cloud-pubsub


# Upgrade ansible to latest stable version published on EPEL repo
- name: upgrade ansible to latest version
  package:
    name: ansible
    state: latest
